apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-apps-ingress
  namespace: ns-apps
  labels:
    app: demo-apps
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: demo-apps.10.0.108.25.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-apps
                port:
                  number: 80

